// Code generated by MockGen. DO NOT EDIT.
// Source: database.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/tusmasoma/go-microservice-k8s/go/services/catalog/entity"
)

// MockCatalogItem is a mock of CatalogItem interface.
type MockCatalogItem struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogItemMockRecorder
}

// MockCatalogItemMockRecorder is the mock recorder for MockCatalogItem.
type MockCatalogItemMockRecorder struct {
	mock *MockCatalogItem
}

// NewMockCatalogItem creates a new mock instance.
func NewMockCatalogItem(ctrl *gomock.Controller) *MockCatalogItem {
	mock := &MockCatalogItem{ctrl: ctrl}
	mock.recorder = &MockCatalogItemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogItem) EXPECT() *MockCatalogItemMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCatalogItem) Create(ctx context.Context, item *entity.CatalogItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCatalogItemMockRecorder) Create(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCatalogItem)(nil).Create), ctx, item)
}

// Delete mocks base method.
func (m *MockCatalogItem) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCatalogItemMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCatalogItem)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockCatalogItem) Get(ctx context.Context, id string) (*entity.CatalogItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*entity.CatalogItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCatalogItemMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCatalogItem)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockCatalogItem) List(ctx context.Context) (entity.CatalogItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(entity.CatalogItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCatalogItemMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCatalogItem)(nil).List), ctx)
}

// ListByIDs mocks base method.
func (m *MockCatalogItem) ListByIDs(ctx context.Context, ids []string) (entity.CatalogItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].(entity.CatalogItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockCatalogItemMockRecorder) ListByIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockCatalogItem)(nil).ListByIDs), ctx, ids)
}

// ListByName mocks base method.
func (m *MockCatalogItem) ListByName(ctx context.Context, name string) (entity.CatalogItems, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByName", ctx, name)
	ret0, _ := ret[0].(entity.CatalogItems)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByName indicates an expected call of ListByName.
func (mr *MockCatalogItemMockRecorder) ListByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByName", reflect.TypeOf((*MockCatalogItem)(nil).ListByName), ctx, name)
}

// Update mocks base method.
func (m *MockCatalogItem) Update(ctx context.Context, item *entity.CatalogItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCatalogItemMockRecorder) Update(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCatalogItem)(nil).Update), ctx, item)
}
