// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/catalog/service.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemRequest) Reset() {
	*x = GetCatalogItemRequest{}
	mi := &file_proto_catalog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemRequest) ProtoMessage() {}

func (x *GetCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCatalogItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CatalogItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemResponse) Reset() {
	*x = GetCatalogItemResponse{}
	mi := &file_proto_catalog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemResponse) ProtoMessage() {}

func (x *GetCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCatalogItemResponse) GetItem() *CatalogItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListCatalogItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsRequest) Reset() {
	*x = ListCatalogItemsRequest{}
	mi := &file_proto_catalog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsRequest) ProtoMessage() {}

func (x *ListCatalogItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{2}
}

type ListCatalogItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsResponse) Reset() {
	*x = ListCatalogItemsResponse{}
	mi := &file_proto_catalog_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsResponse) ProtoMessage() {}

func (x *ListCatalogItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListCatalogItemsResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListCatalogItemsByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsByNameRequest) Reset() {
	*x = ListCatalogItemsByNameRequest{}
	mi := &file_proto_catalog_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsByNameRequest) ProtoMessage() {}

func (x *ListCatalogItemsByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsByNameRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListCatalogItemsByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCatalogItemsByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsByNameResponse) Reset() {
	*x = ListCatalogItemsByNameResponse{}
	mi := &file_proto_catalog_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsByNameResponse) ProtoMessage() {}

func (x *ListCatalogItemsByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsByNameResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListCatalogItemsByNameResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListCatalogItemsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsByIDsRequest) Reset() {
	*x = ListCatalogItemsByIDsRequest{}
	mi := &file_proto_catalog_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsByIDsRequest) ProtoMessage() {}

func (x *ListCatalogItemsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsByIDsRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListCatalogItemsByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListCatalogItemsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsByIDsResponse) Reset() {
	*x = ListCatalogItemsByIDsResponse{}
	mi := &file_proto_catalog_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsByIDsResponse) ProtoMessage() {}

func (x *ListCatalogItemsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsByIDsResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListCatalogItemsByIDsResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogItemRequest) Reset() {
	*x = CreateCatalogItemRequest{}
	mi := &file_proto_catalog_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogItemRequest) ProtoMessage() {}

func (x *CreateCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*CreateCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCatalogItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCatalogItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogItemResponse) Reset() {
	*x = CreateCatalogItemResponse{}
	mi := &file_proto_catalog_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogItemResponse) ProtoMessage() {}

func (x *CreateCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*CreateCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{9}
}

type UpdateCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatalogItemRequest) Reset() {
	*x = UpdateCatalogItemRequest{}
	mi := &file_proto_catalog_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatalogItemRequest) ProtoMessage() {}

func (x *UpdateCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCatalogItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCatalogItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCatalogItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatalogItemResponse) Reset() {
	*x = UpdateCatalogItemResponse{}
	mi := &file_proto_catalog_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatalogItemResponse) ProtoMessage() {}

func (x *UpdateCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{11}
}

type DeleteCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatalogItemRequest) Reset() {
	*x = DeleteCatalogItemRequest{}
	mi := &file_proto_catalog_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatalogItemRequest) ProtoMessage() {}

func (x *DeleteCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCatalogItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatalogItemResponse) Reset() {
	*x = DeleteCatalogItemResponse{}
	mi := &file_proto_catalog_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatalogItemResponse) ProtoMessage() {}

func (x *DeleteCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_service_proto_rawDescGZIP(), []int{13}
}

var File_proto_catalog_service_proto protoreflect.FileDescriptor

const file_proto_catalog_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/catalog/service.proto\x12\acatalog\x1a\x1bproto/catalog/catalog.proto\"'\n" +
	"\x15GetCatalogItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x16GetCatalogItemResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.catalog.CatalogItemR\x04item\"\x19\n" +
	"\x17ListCatalogItemsRequest\"F\n" +
	"\x18ListCatalogItemsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.catalog.CatalogItemR\x05items\"3\n" +
	"\x1dListCatalogItemsByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"L\n" +
	"\x1eListCatalogItemsByNameResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.catalog.CatalogItemR\x05items\"0\n" +
	"\x1cListCatalogItemsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"K\n" +
	"\x1dListCatalogItemsByIDsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.catalog.CatalogItemR\x05items\"D\n" +
	"\x18CreateCatalogItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\"\x1b\n" +
	"\x19CreateCatalogItemResponse\"T\n" +
	"\x18UpdateCatalogItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"\x1b\n" +
	"\x19UpdateCatalogItemResponse\"*\n" +
	"\x18DeleteCatalogItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteCatalogItemResponse2\xa3\x05\n" +
	"\x0eCatalogService\x12Q\n" +
	"\x0eGetCatalogItem\x12\x1e.catalog.GetCatalogItemRequest\x1a\x1f.catalog.GetCatalogItemResponse\x12W\n" +
	"\x10ListCatalogItems\x12 .catalog.ListCatalogItemsRequest\x1a!.catalog.ListCatalogItemsResponse\x12i\n" +
	"\x16ListCatalogItemsByName\x12&.catalog.ListCatalogItemsByNameRequest\x1a'.catalog.ListCatalogItemsByNameResponse\x12f\n" +
	"\x15ListCatalogItemsByIDs\x12%.catalog.ListCatalogItemsByIDsRequest\x1a&.catalog.ListCatalogItemsByIDsResponse\x12Z\n" +
	"\x11CreateCatalogItem\x12!.catalog.CreateCatalogItemRequest\x1a\".catalog.CreateCatalogItemResponse\x12Z\n" +
	"\x11UpdateCatalogItem\x12!.catalog.UpdateCatalogItemRequest\x1a\".catalog.UpdateCatalogItemResponse\x12Z\n" +
	"\x11DeleteCatalogItem\x12!.catalog.DeleteCatalogItemRequest\x1a\".catalog.DeleteCatalogItemResponseB\x0fZ\rproto/catalogb\x06proto3"

var (
	file_proto_catalog_service_proto_rawDescOnce sync.Once
	file_proto_catalog_service_proto_rawDescData []byte
)

func file_proto_catalog_service_proto_rawDescGZIP() []byte {
	file_proto_catalog_service_proto_rawDescOnce.Do(func() {
		file_proto_catalog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_service_proto_rawDesc), len(file_proto_catalog_service_proto_rawDesc)))
	})
	return file_proto_catalog_service_proto_rawDescData
}

var file_proto_catalog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_catalog_service_proto_goTypes = []any{
	(*GetCatalogItemRequest)(nil),          // 0: catalog.GetCatalogItemRequest
	(*GetCatalogItemResponse)(nil),         // 1: catalog.GetCatalogItemResponse
	(*ListCatalogItemsRequest)(nil),        // 2: catalog.ListCatalogItemsRequest
	(*ListCatalogItemsResponse)(nil),       // 3: catalog.ListCatalogItemsResponse
	(*ListCatalogItemsByNameRequest)(nil),  // 4: catalog.ListCatalogItemsByNameRequest
	(*ListCatalogItemsByNameResponse)(nil), // 5: catalog.ListCatalogItemsByNameResponse
	(*ListCatalogItemsByIDsRequest)(nil),   // 6: catalog.ListCatalogItemsByIDsRequest
	(*ListCatalogItemsByIDsResponse)(nil),  // 7: catalog.ListCatalogItemsByIDsResponse
	(*CreateCatalogItemRequest)(nil),       // 8: catalog.CreateCatalogItemRequest
	(*CreateCatalogItemResponse)(nil),      // 9: catalog.CreateCatalogItemResponse
	(*UpdateCatalogItemRequest)(nil),       // 10: catalog.UpdateCatalogItemRequest
	(*UpdateCatalogItemResponse)(nil),      // 11: catalog.UpdateCatalogItemResponse
	(*DeleteCatalogItemRequest)(nil),       // 12: catalog.DeleteCatalogItemRequest
	(*DeleteCatalogItemResponse)(nil),      // 13: catalog.DeleteCatalogItemResponse
	(*CatalogItem)(nil),                    // 14: catalog.CatalogItem
}
var file_proto_catalog_service_proto_depIdxs = []int32{
	14, // 0: catalog.GetCatalogItemResponse.item:type_name -> catalog.CatalogItem
	14, // 1: catalog.ListCatalogItemsResponse.items:type_name -> catalog.CatalogItem
	14, // 2: catalog.ListCatalogItemsByNameResponse.items:type_name -> catalog.CatalogItem
	14, // 3: catalog.ListCatalogItemsByIDsResponse.items:type_name -> catalog.CatalogItem
	0,  // 4: catalog.CatalogService.GetCatalogItem:input_type -> catalog.GetCatalogItemRequest
	2,  // 5: catalog.CatalogService.ListCatalogItems:input_type -> catalog.ListCatalogItemsRequest
	4,  // 6: catalog.CatalogService.ListCatalogItemsByName:input_type -> catalog.ListCatalogItemsByNameRequest
	6,  // 7: catalog.CatalogService.ListCatalogItemsByIDs:input_type -> catalog.ListCatalogItemsByIDsRequest
	8,  // 8: catalog.CatalogService.CreateCatalogItem:input_type -> catalog.CreateCatalogItemRequest
	10, // 9: catalog.CatalogService.UpdateCatalogItem:input_type -> catalog.UpdateCatalogItemRequest
	12, // 10: catalog.CatalogService.DeleteCatalogItem:input_type -> catalog.DeleteCatalogItemRequest
	1,  // 11: catalog.CatalogService.GetCatalogItem:output_type -> catalog.GetCatalogItemResponse
	3,  // 12: catalog.CatalogService.ListCatalogItems:output_type -> catalog.ListCatalogItemsResponse
	5,  // 13: catalog.CatalogService.ListCatalogItemsByName:output_type -> catalog.ListCatalogItemsByNameResponse
	7,  // 14: catalog.CatalogService.ListCatalogItemsByIDs:output_type -> catalog.ListCatalogItemsByIDsResponse
	9,  // 15: catalog.CatalogService.CreateCatalogItem:output_type -> catalog.CreateCatalogItemResponse
	11, // 16: catalog.CatalogService.UpdateCatalogItem:output_type -> catalog.UpdateCatalogItemResponse
	13, // 17: catalog.CatalogService.DeleteCatalogItem:output_type -> catalog.DeleteCatalogItemResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_catalog_service_proto_init() }
func file_proto_catalog_service_proto_init() {
	if File_proto_catalog_service_proto != nil {
		return
	}
	file_proto_catalog_catalog_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_service_proto_rawDesc), len(file_proto_catalog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_service_proto_goTypes,
		DependencyIndexes: file_proto_catalog_service_proto_depIdxs,
		MessageInfos:      file_proto_catalog_service_proto_msgTypes,
	}.Build()
	File_proto_catalog_service_proto = out.File
	file_proto_catalog_service_proto_goTypes = nil
	file_proto_catalog_service_proto_depIdxs = nil
}
