apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: somakimura/mysql-service:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: MYSQL_DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: shared-config
              key: MYSQL_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    # storageClassName: "my-storage-class" -> ここでstorageClassを指定しないと、デフォルトのStorageClassが割り当てられる (kubectl get storageclassで確認可能)
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi