version: "3"

services:
  mysql:
    container_name: mysql
    build:
      context: ../migrations
      dockerfile: ./Dockerfile
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - microservices-net
  commerce-gateway:
    build:
      context: ./commerce-gateway
      dockerfile: ./Dockerfile
    container_name: commerce-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    # depends_on:
    #   - customer-service
    #   - catalog-service
    networks:
      - microservices-net
  customer-service:
    build:
      context: ./customer
      dockerfile: ./Dockerfile
    container_name: customer-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - microservices-net
  catalog-service:
    build:
      context: ./catalog
      dockerfile: ./Dockerfile
    container_name: catalog-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - microservices-net
  order-service:
    build:
      context: ./order
      dockerfile: ./Dockerfile
    container_name: order-service
    ports:
      - "8083:8083"
    # environment:
    #   - CUSTOMER_SERVICE_URL=http://customer-service:8080
    #   - CATALOG_SERVICE_URL=http://catalog-service:8080
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - microservices-net

  # swagger-ui:
  #   container_name: chat_swagger_ui
  #   image: swaggerapi/swagger-ui:latest
  #   ports:
  #     - 3000:8080
  #   environment:
  #     SWAGGER_JSON: /api/api-document.yaml
  #   volumes:
  #     - ./docs/api-document.yaml:/api/api-document.yaml:ro
networks:
  microservices-net:
    driver: bridge
volumes:
  db-data:
    driver: local