// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/customer/customer.proto

package customer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountryCode int32

const (
	CountryCode_COUNTRY_CODE_UNSPECIFIED CountryCode = 0
	CountryCode_USA                      CountryCode = 1
	CountryCode_JPN                      CountryCode = 2
	CountryCode_DEU                      CountryCode = 3
	CountryCode_FRA                      CountryCode = 4
	CountryCode_GBR                      CountryCode = 5
	CountryCode_CAN                      CountryCode = 6
	CountryCode_AUS                      CountryCode = 7
	CountryCode_ITA                      CountryCode = 8
	CountryCode_BRA                      CountryCode = 9
	CountryCode_KOR                      CountryCode = 10
	CountryCode_CHN                      CountryCode = 11
	CountryCode_IND                      CountryCode = 12
	CountryCode_MEX                      CountryCode = 13
	CountryCode_RUS                      CountryCode = 14
	CountryCode_ESP                      CountryCode = 15
	CountryCode_NLD                      CountryCode = 16
	CountryCode_SWE                      CountryCode = 17
	CountryCode_CHE                      CountryCode = 18
	CountryCode_ARG                      CountryCode = 19
	CountryCode_ZAF                      CountryCode = 20
)

// Enum value maps for CountryCode.
var (
	CountryCode_name = map[int32]string{
		0:  "COUNTRY_CODE_UNSPECIFIED",
		1:  "USA",
		2:  "JPN",
		3:  "DEU",
		4:  "FRA",
		5:  "GBR",
		6:  "CAN",
		7:  "AUS",
		8:  "ITA",
		9:  "BRA",
		10: "KOR",
		11: "CHN",
		12: "IND",
		13: "MEX",
		14: "RUS",
		15: "ESP",
		16: "NLD",
		17: "SWE",
		18: "CHE",
		19: "ARG",
		20: "ZAF",
	}
	CountryCode_value = map[string]int32{
		"COUNTRY_CODE_UNSPECIFIED": 0,
		"USA":                      1,
		"JPN":                      2,
		"DEU":                      3,
		"FRA":                      4,
		"GBR":                      5,
		"CAN":                      6,
		"AUS":                      7,
		"ITA":                      8,
		"BRA":                      9,
		"KOR":                      10,
		"CHN":                      11,
		"IND":                      12,
		"MEX":                      13,
		"RUS":                      14,
		"ESP":                      15,
		"NLD":                      16,
		"SWE":                      17,
		"CHE":                      18,
		"ARG":                      19,
		"ZAF":                      20,
	}
)

func (x CountryCode) Enum() *CountryCode {
	p := new(CountryCode)
	*p = x
	return p
}

func (x CountryCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CountryCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_customer_customer_proto_enumTypes[0].Descriptor()
}

func (CountryCode) Type() protoreflect.EnumType {
	return &file_proto_customer_customer_proto_enumTypes[0]
}

func (x CountryCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CountryCode.Descriptor instead.
func (CountryCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_customer_customer_proto_rawDescGZIP(), []int{0}
}

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode   CountryCode            `protobuf:"varint,6,opt,name=country_code,json=countryCode,proto3,enum=customer.CountryCode" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_proto_customer_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Customer) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Customer) GetCountryCode() CountryCode {
	if x != nil {
		return x.CountryCode
	}
	return CountryCode_COUNTRY_CODE_UNSPECIFIED
}

var File_proto_customer_customer_proto protoreflect.FileDescriptor

const file_proto_customer_customer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/customer/customer.proto\x12\bcustomer\"\xaa\x01\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x128\n" +
	"\fcountry_code\x18\x06 \x01(\x0e2\x15.customer.CountryCodeR\vcountryCode*\xdf\x01\n" +
	"\vCountryCode\x12\x1c\n" +
	"\x18COUNTRY_CODE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03USA\x10\x01\x12\a\n" +
	"\x03JPN\x10\x02\x12\a\n" +
	"\x03DEU\x10\x03\x12\a\n" +
	"\x03FRA\x10\x04\x12\a\n" +
	"\x03GBR\x10\x05\x12\a\n" +
	"\x03CAN\x10\x06\x12\a\n" +
	"\x03AUS\x10\a\x12\a\n" +
	"\x03ITA\x10\b\x12\a\n" +
	"\x03BRA\x10\t\x12\a\n" +
	"\x03KOR\x10\n" +
	"\x12\a\n" +
	"\x03CHN\x10\v\x12\a\n" +
	"\x03IND\x10\f\x12\a\n" +
	"\x03MEX\x10\r\x12\a\n" +
	"\x03RUS\x10\x0e\x12\a\n" +
	"\x03ESP\x10\x0f\x12\a\n" +
	"\x03NLD\x10\x10\x12\a\n" +
	"\x03SWE\x10\x11\x12\a\n" +
	"\x03CHE\x10\x12\x12\a\n" +
	"\x03ARG\x10\x13\x12\a\n" +
	"\x03ZAF\x10\x14B\x10Z\x0eproto/customerb\x06proto3"

var (
	file_proto_customer_customer_proto_rawDescOnce sync.Once
	file_proto_customer_customer_proto_rawDescData []byte
)

func file_proto_customer_customer_proto_rawDescGZIP() []byte {
	file_proto_customer_customer_proto_rawDescOnce.Do(func() {
		file_proto_customer_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_customer_customer_proto_rawDesc), len(file_proto_customer_customer_proto_rawDesc)))
	})
	return file_proto_customer_customer_proto_rawDescData
}

var file_proto_customer_customer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_customer_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_customer_customer_proto_goTypes = []any{
	(CountryCode)(0), // 0: customer.CountryCode
	(*Customer)(nil), // 1: customer.Customer
}
var file_proto_customer_customer_proto_depIdxs = []int32{
	0, // 0: customer.Customer.country_code:type_name -> customer.CountryCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_customer_customer_proto_init() }
func file_proto_customer_customer_proto_init() {
	if File_proto_customer_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_customer_customer_proto_rawDesc), len(file_proto_customer_customer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_customer_customer_proto_goTypes,
		DependencyIndexes: file_proto_customer_customer_proto_depIdxs,
		EnumInfos:         file_proto_customer_customer_proto_enumTypes,
		MessageInfos:      file_proto_customer_customer_proto_msgTypes,
	}.Build()
	File_proto_customer_customer_proto = out.File
	file_proto_customer_customer_proto_goTypes = nil
	file_proto_customer_customer_proto_depIdxs = nil
}
