// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.2
// source: proto/customer/customer.proto

package customer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountryCode int32

const (
	CountryCode_COUNTRY_CODE_UNSPECIFIED CountryCode = 0
	CountryCode_USA                      CountryCode = 1
	CountryCode_JPN                      CountryCode = 2
	CountryCode_DEU                      CountryCode = 3
	CountryCode_FRA                      CountryCode = 4
	CountryCode_GBR                      CountryCode = 5
	CountryCode_CAN                      CountryCode = 6
	CountryCode_AUS                      CountryCode = 7
	CountryCode_ITA                      CountryCode = 8
	CountryCode_BRA                      CountryCode = 9
	CountryCode_KOR                      CountryCode = 10
	CountryCode_CHN                      CountryCode = 11
	CountryCode_IND                      CountryCode = 12
	CountryCode_MEX                      CountryCode = 13
	CountryCode_RUS                      CountryCode = 14
	CountryCode_ESP                      CountryCode = 15
	CountryCode_NLD                      CountryCode = 16
	CountryCode_SWE                      CountryCode = 17
	CountryCode_CHE                      CountryCode = 18
	CountryCode_ARG                      CountryCode = 19
	CountryCode_ZAF                      CountryCode = 20
)

// Enum value maps for CountryCode.
var (
	CountryCode_name = map[int32]string{
		0:  "COUNTRY_CODE_UNSPECIFIED",
		1:  "USA",
		2:  "JPN",
		3:  "DEU",
		4:  "FRA",
		5:  "GBR",
		6:  "CAN",
		7:  "AUS",
		8:  "ITA",
		9:  "BRA",
		10: "KOR",
		11: "CHN",
		12: "IND",
		13: "MEX",
		14: "RUS",
		15: "ESP",
		16: "NLD",
		17: "SWE",
		18: "CHE",
		19: "ARG",
		20: "ZAF",
	}
	CountryCode_value = map[string]int32{
		"COUNTRY_CODE_UNSPECIFIED": 0,
		"USA":                      1,
		"JPN":                      2,
		"DEU":                      3,
		"FRA":                      4,
		"GBR":                      5,
		"CAN":                      6,
		"AUS":                      7,
		"ITA":                      8,
		"BRA":                      9,
		"KOR":                      10,
		"CHN":                      11,
		"IND":                      12,
		"MEX":                      13,
		"RUS":                      14,
		"ESP":                      15,
		"NLD":                      16,
		"SWE":                      17,
		"CHE":                      18,
		"ARG":                      19,
		"ZAF":                      20,
	}
)

func (x CountryCode) Enum() *CountryCode {
	p := new(CountryCode)
	*p = x
	return p
}

func (x CountryCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CountryCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_customer_customer_proto_enumTypes[0].Descriptor()
}

func (CountryCode) Type() protoreflect.EnumType {
	return &file_proto_customer_customer_proto_enumTypes[0]
}

func (x CountryCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CountryCode.Descriptor instead.
func (CountryCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_customer_customer_proto_rawDescGZIP(), []int{0}
}

type Customer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email       string      `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Street      string      `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	City        string      `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode CountryCode `protobuf:"varint,6,opt,name=country_code,json=countryCode,proto3,enum=customer.CountryCode" json:"country_code,omitempty"`
}

func (x *Customer) Reset() {
	*x = Customer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_customer_customer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_customer_customer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_proto_customer_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Customer) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Customer) GetCountryCode() CountryCode {
	if x != nil {
		return x.CountryCode
	}
	return CountryCode_COUNTRY_CODE_UNSPECIFIED
}

var File_proto_customer_customer_proto protoreflect.FileDescriptor

var file_proto_customer_customer_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0xaa, 0x01, 0x0a, 0x08, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x0c,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0xdf, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x52,
	0x59, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x53, 0x41, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x4a, 0x50, 0x4e, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x45, 0x55, 0x10, 0x03, 0x12,
	0x07, 0x0a, 0x03, 0x46, 0x52, 0x41, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x42, 0x52, 0x10,
	0x05, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x41, 0x4e, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x55,
	0x53, 0x10, 0x07, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x54, 0x41, 0x10, 0x08, 0x12, 0x07, 0x0a, 0x03,
	0x42, 0x52, 0x41, 0x10, 0x09, 0x12, 0x07, 0x0a, 0x03, 0x4b, 0x4f, 0x52, 0x10, 0x0a, 0x12, 0x07,
	0x0a, 0x03, 0x43, 0x48, 0x4e, 0x10, 0x0b, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x44, 0x10, 0x0c,
	0x12, 0x07, 0x0a, 0x03, 0x4d, 0x45, 0x58, 0x10, 0x0d, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x55, 0x53,
	0x10, 0x0e, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x53, 0x50, 0x10, 0x0f, 0x12, 0x07, 0x0a, 0x03, 0x4e,
	0x4c, 0x44, 0x10, 0x10, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x57, 0x45, 0x10, 0x11, 0x12, 0x07, 0x0a,
	0x03, 0x43, 0x48, 0x45, 0x10, 0x12, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x52, 0x47, 0x10, 0x13, 0x12,
	0x07, 0x0a, 0x03, 0x5a, 0x41, 0x46, 0x10, 0x14, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_customer_customer_proto_rawDescOnce sync.Once
	file_proto_customer_customer_proto_rawDescData = file_proto_customer_customer_proto_rawDesc
)

func file_proto_customer_customer_proto_rawDescGZIP() []byte {
	file_proto_customer_customer_proto_rawDescOnce.Do(func() {
		file_proto_customer_customer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_customer_customer_proto_rawDescData)
	})
	return file_proto_customer_customer_proto_rawDescData
}

var file_proto_customer_customer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_customer_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_customer_customer_proto_goTypes = []interface{}{
	(CountryCode)(0), // 0: customer.CountryCode
	(*Customer)(nil), // 1: customer.Customer
}
var file_proto_customer_customer_proto_depIdxs = []int32{
	0, // 0: customer.Customer.country_code:type_name -> customer.CountryCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_customer_customer_proto_init() }
func file_proto_customer_customer_proto_init() {
	if File_proto_customer_customer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_customer_customer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Customer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_customer_customer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_customer_customer_proto_goTypes,
		DependencyIndexes: file_proto_customer_customer_proto_depIdxs,
		EnumInfos:         file_proto_customer_customer_proto_enumTypes,
		MessageInfos:      file_proto_customer_customer_proto_msgTypes,
	}.Build()
	File_proto_customer_customer_proto = out.File
	file_proto_customer_customer_proto_rawDesc = nil
	file_proto_customer_customer_proto_goTypes = nil
	file_proto_customer_customer_proto_depIdxs = nil
}
