syntax = "proto3";

package customer;

option go_package = "proto/customer";

message Customer {
    string id = 1;
    string name = 2;
    string email = 3;
    string street = 4;
    string city = 5;
    CountryCode country_code = 6;
}

enum CountryCode {
    COUNTRY_CODE_UNSPECIFIED = 0;
    USA = 1;
    JPN = 2;
    DEU = 3;
    FRA = 4;
    GBR = 5;
    CAN = 6;
    AUS = 7;
    ITA = 8;
    BRA = 9;
    KOR = 10;
    CHN = 11;
    IND = 12;
    MEX = 13;
    RUS = 14;
    ESP = 15;
    NLD = 16;
    SWE = 17;
    CHE = 18;
    ARG = 19;
    ZAF = 20;
  }