// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/web/catalog.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemRequest) Reset() {
	*x = GetCatalogItemRequest{}
	mi := &file_proto_web_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemRequest) ProtoMessage() {}

func (x *GetCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{0}
}

type GetCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CatalogItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemResponse) Reset() {
	*x = GetCatalogItemResponse{}
	mi := &file_proto_web_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemResponse) ProtoMessage() {}

func (x *GetCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetCatalogItemResponse) GetItem() *CatalogItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListCatalogItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsRequest) Reset() {
	*x = ListCatalogItemsRequest{}
	mi := &file_proto_web_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsRequest) ProtoMessage() {}

func (x *ListCatalogItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{2}
}

type ListCatalogItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsResponse) Reset() {
	*x = ListCatalogItemsResponse{}
	mi := &file_proto_web_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsResponse) ProtoMessage() {}

func (x *ListCatalogItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListCatalogItemsResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListCatalogItemsByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsByNameRequest) Reset() {
	*x = ListCatalogItemsByNameRequest{}
	mi := &file_proto_web_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsByNameRequest) ProtoMessage() {}

func (x *ListCatalogItemsByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsByNameRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListCatalogItemsByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCatalogItemsByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsByNameResponse) Reset() {
	*x = ListCatalogItemsByNameResponse{}
	mi := &file_proto_web_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsByNameResponse) ProtoMessage() {}

func (x *ListCatalogItemsByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsByNameResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *ListCatalogItemsByNameResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListCatalogItemsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsByIDsRequest) Reset() {
	*x = ListCatalogItemsByIDsRequest{}
	mi := &file_proto_web_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsByIDsRequest) ProtoMessage() {}

func (x *ListCatalogItemsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsByIDsRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListCatalogItemsByIDsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListCatalogItemsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsByIDsResponse) Reset() {
	*x = ListCatalogItemsByIDsResponse{}
	mi := &file_proto_web_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsByIDsResponse) ProtoMessage() {}

func (x *ListCatalogItemsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsByIDsResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ListCatalogItemsByIDsResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogItemRequest) Reset() {
	*x = CreateCatalogItemRequest{}
	mi := &file_proto_web_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogItemRequest) ProtoMessage() {}

func (x *CreateCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*CreateCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCatalogItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCatalogItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatalogItemResponse) Reset() {
	*x = CreateCatalogItemResponse{}
	mi := &file_proto_web_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatalogItemResponse) ProtoMessage() {}

func (x *CreateCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*CreateCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{9}
}

type UpdateCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatalogItemRequest) Reset() {
	*x = UpdateCatalogItemRequest{}
	mi := &file_proto_web_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatalogItemRequest) ProtoMessage() {}

func (x *UpdateCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCatalogItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCatalogItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatalogItemResponse) Reset() {
	*x = UpdateCatalogItemResponse{}
	mi := &file_proto_web_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatalogItemResponse) ProtoMessage() {}

func (x *UpdateCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{11}
}

type DeleteCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatalogItemRequest) Reset() {
	*x = DeleteCatalogItemRequest{}
	mi := &file_proto_web_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatalogItemRequest) ProtoMessage() {}

func (x *DeleteCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{12}
}

type DeleteCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatalogItemResponse) Reset() {
	*x = DeleteCatalogItemResponse{}
	mi := &file_proto_web_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatalogItemResponse) ProtoMessage() {}

func (x *DeleteCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{13}
}

type CatalogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatalogItem) Reset() {
	*x = CatalogItem{}
	mi := &file_proto_web_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogItem) ProtoMessage() {}

func (x *CatalogItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogItem.ProtoReflect.Descriptor instead.
func (*CatalogItem) Descriptor() ([]byte, []int) {
	return file_proto_web_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *CatalogItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CatalogItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CatalogItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_proto_web_catalog_proto protoreflect.FileDescriptor

const file_proto_web_catalog_proto_rawDesc = "" +
	"\n" +
	"\x17proto/web/catalog.proto\x12\x03web\"\x17\n" +
	"\x15GetCatalogItemRequest\">\n" +
	"\x16GetCatalogItemResponse\x12$\n" +
	"\x04item\x18\x01 \x01(\v2\x10.web.CatalogItemR\x04item\"\x19\n" +
	"\x17ListCatalogItemsRequest\"B\n" +
	"\x18ListCatalogItemsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.web.CatalogItemR\x05items\"3\n" +
	"\x1dListCatalogItemsByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x1eListCatalogItemsByNameResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.web.CatalogItemR\x05items\"0\n" +
	"\x1cListCatalogItemsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"G\n" +
	"\x1dListCatalogItemsByIDsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.web.CatalogItemR\x05items\"D\n" +
	"\x18CreateCatalogItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\"\x1b\n" +
	"\x19CreateCatalogItemResponse\"D\n" +
	"\x18UpdateCatalogItemRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"\x1b\n" +
	"\x19UpdateCatalogItemResponse\"\x1a\n" +
	"\x18DeleteCatalogItemRequest\"\x1b\n" +
	"\x19DeleteCatalogItemResponse\"G\n" +
	"\vCatalogItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05priceB\vZ\tproto/webb\x06proto3"

var (
	file_proto_web_catalog_proto_rawDescOnce sync.Once
	file_proto_web_catalog_proto_rawDescData []byte
)

func file_proto_web_catalog_proto_rawDescGZIP() []byte {
	file_proto_web_catalog_proto_rawDescOnce.Do(func() {
		file_proto_web_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_web_catalog_proto_rawDesc), len(file_proto_web_catalog_proto_rawDesc)))
	})
	return file_proto_web_catalog_proto_rawDescData
}

var file_proto_web_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_web_catalog_proto_goTypes = []any{
	(*GetCatalogItemRequest)(nil),          // 0: web.GetCatalogItemRequest
	(*GetCatalogItemResponse)(nil),         // 1: web.GetCatalogItemResponse
	(*ListCatalogItemsRequest)(nil),        // 2: web.ListCatalogItemsRequest
	(*ListCatalogItemsResponse)(nil),       // 3: web.ListCatalogItemsResponse
	(*ListCatalogItemsByNameRequest)(nil),  // 4: web.ListCatalogItemsByNameRequest
	(*ListCatalogItemsByNameResponse)(nil), // 5: web.ListCatalogItemsByNameResponse
	(*ListCatalogItemsByIDsRequest)(nil),   // 6: web.ListCatalogItemsByIDsRequest
	(*ListCatalogItemsByIDsResponse)(nil),  // 7: web.ListCatalogItemsByIDsResponse
	(*CreateCatalogItemRequest)(nil),       // 8: web.CreateCatalogItemRequest
	(*CreateCatalogItemResponse)(nil),      // 9: web.CreateCatalogItemResponse
	(*UpdateCatalogItemRequest)(nil),       // 10: web.UpdateCatalogItemRequest
	(*UpdateCatalogItemResponse)(nil),      // 11: web.UpdateCatalogItemResponse
	(*DeleteCatalogItemRequest)(nil),       // 12: web.DeleteCatalogItemRequest
	(*DeleteCatalogItemResponse)(nil),      // 13: web.DeleteCatalogItemResponse
	(*CatalogItem)(nil),                    // 14: web.CatalogItem
}
var file_proto_web_catalog_proto_depIdxs = []int32{
	14, // 0: web.GetCatalogItemResponse.item:type_name -> web.CatalogItem
	14, // 1: web.ListCatalogItemsResponse.items:type_name -> web.CatalogItem
	14, // 2: web.ListCatalogItemsByNameResponse.items:type_name -> web.CatalogItem
	14, // 3: web.ListCatalogItemsByIDsResponse.items:type_name -> web.CatalogItem
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_web_catalog_proto_init() }
func file_proto_web_catalog_proto_init() {
	if File_proto_web_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_web_catalog_proto_rawDesc), len(file_proto_web_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_web_catalog_proto_goTypes,
		DependencyIndexes: file_proto_web_catalog_proto_depIdxs,
		MessageInfos:      file_proto_web_catalog_proto_msgTypes,
	}.Build()
	File_proto_web_catalog_proto = out.File
	file_proto_web_catalog_proto_goTypes = nil
	file_proto_web_catalog_proto_depIdxs = nil
}
