// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/web/customer.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountryCode int32

const (
	CountryCode_COUNTRY_CODE_UNSPECIFIED CountryCode = 0
	CountryCode_USA                      CountryCode = 1
	CountryCode_JPN                      CountryCode = 2
	CountryCode_DEU                      CountryCode = 3
	CountryCode_FRA                      CountryCode = 4
	CountryCode_GBR                      CountryCode = 5
	CountryCode_CAN                      CountryCode = 6
	CountryCode_AUS                      CountryCode = 7
	CountryCode_ITA                      CountryCode = 8
	CountryCode_BRA                      CountryCode = 9
	CountryCode_KOR                      CountryCode = 10
	CountryCode_CHN                      CountryCode = 11
	CountryCode_IND                      CountryCode = 12
	CountryCode_MEX                      CountryCode = 13
	CountryCode_RUS                      CountryCode = 14
	CountryCode_ESP                      CountryCode = 15
	CountryCode_NLD                      CountryCode = 16
	CountryCode_SWE                      CountryCode = 17
	CountryCode_CHE                      CountryCode = 18
	CountryCode_ARG                      CountryCode = 19
	CountryCode_ZAF                      CountryCode = 20
)

// Enum value maps for CountryCode.
var (
	CountryCode_name = map[int32]string{
		0:  "COUNTRY_CODE_UNSPECIFIED",
		1:  "USA",
		2:  "JPN",
		3:  "DEU",
		4:  "FRA",
		5:  "GBR",
		6:  "CAN",
		7:  "AUS",
		8:  "ITA",
		9:  "BRA",
		10: "KOR",
		11: "CHN",
		12: "IND",
		13: "MEX",
		14: "RUS",
		15: "ESP",
		16: "NLD",
		17: "SWE",
		18: "CHE",
		19: "ARG",
		20: "ZAF",
	}
	CountryCode_value = map[string]int32{
		"COUNTRY_CODE_UNSPECIFIED": 0,
		"USA":                      1,
		"JPN":                      2,
		"DEU":                      3,
		"FRA":                      4,
		"GBR":                      5,
		"CAN":                      6,
		"AUS":                      7,
		"ITA":                      8,
		"BRA":                      9,
		"KOR":                      10,
		"CHN":                      11,
		"IND":                      12,
		"MEX":                      13,
		"RUS":                      14,
		"ESP":                      15,
		"NLD":                      16,
		"SWE":                      17,
		"CHE":                      18,
		"ARG":                      19,
		"ZAF":                      20,
	}
)

func (x CountryCode) Enum() *CountryCode {
	p := new(CountryCode)
	*p = x
	return p
}

func (x CountryCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CountryCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_web_customer_proto_enumTypes[0].Descriptor()
}

func (CountryCode) Type() protoreflect.EnumType {
	return &file_proto_web_customer_proto_enumTypes[0]
}

func (x CountryCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CountryCode.Descriptor instead.
func (CountryCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{0}
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_proto_web_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{0}
}

type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_proto_web_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{1}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type ListCustomersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersRequest) Reset() {
	*x = ListCustomersRequest{}
	mi := &file_proto_web_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersRequest) ProtoMessage() {}

func (x *ListCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersRequest.ProtoReflect.Descriptor instead.
func (*ListCustomersRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{2}
}

type ListCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersResponse) Reset() {
	*x = ListCustomersResponse{}
	mi := &file_proto_web_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersResponse) ProtoMessage() {}

func (x *ListCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersResponse.ProtoReflect.Descriptor instead.
func (*ListCustomersResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{3}
}

func (x *ListCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode   CountryCode            `protobuf:"varint,5,opt,name=country_code,json=countryCode,proto3,enum=web.CountryCode" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_proto_web_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *CreateCustomerRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateCustomerRequest) GetCountryCode() CountryCode {
	if x != nil {
		return x.CountryCode
	}
	return CountryCode_COUNTRY_CODE_UNSPECIFIED
}

type CreateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_proto_web_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{5}
}

type UpdateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode   CountryCode            `protobuf:"varint,6,opt,name=country_code,json=countryCode,proto3,enum=web.CountryCode" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerRequest) Reset() {
	*x = UpdateCustomerRequest{}
	mi := &file_proto_web_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerRequest) ProtoMessage() {}

func (x *UpdateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateCustomerRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *UpdateCustomerRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateCustomerRequest) GetCountryCode() CountryCode {
	if x != nil {
		return x.CountryCode
	}
	return CountryCode_COUNTRY_CODE_UNSPECIFIED
}

type UpdateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerResponse) Reset() {
	*x = UpdateCustomerResponse{}
	mi := &file_proto_web_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerResponse) ProtoMessage() {}

func (x *UpdateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerResponse.ProtoReflect.Descriptor instead.
func (*UpdateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{7}
}

type DeleteCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerRequest) Reset() {
	*x = DeleteCustomerRequest{}
	mi := &file_proto_web_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerRequest) ProtoMessage() {}

func (x *DeleteCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerRequest.ProtoReflect.Descriptor instead.
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{8}
}

type DeleteCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerResponse) Reset() {
	*x = DeleteCustomerResponse{}
	mi := &file_proto_web_customer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerResponse) ProtoMessage() {}

func (x *DeleteCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerResponse.ProtoReflect.Descriptor instead.
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{9}
}

type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Street        string                 `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode   CountryCode            `protobuf:"varint,6,opt,name=country_code,json=countryCode,proto3,enum=web.CountryCode" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_proto_web_customer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_web_customer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_proto_web_customer_proto_rawDescGZIP(), []int{10}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Customer) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Customer) GetCountryCode() CountryCode {
	if x != nil {
		return x.CountryCode
	}
	return CountryCode_COUNTRY_CODE_UNSPECIFIED
}

var File_proto_web_customer_proto protoreflect.FileDescriptor

const file_proto_web_customer_proto_rawDesc = "" +
	"\n" +
	"\x18proto/web/customer.proto\x12\x03web\"\x14\n" +
	"\x12GetCustomerRequest\"@\n" +
	"\x13GetCustomerResponse\x12)\n" +
	"\bcustomer\x18\x01 \x01(\v2\r.web.CustomerR\bcustomer\"\x16\n" +
	"\x14ListCustomersRequest\"D\n" +
	"\x15ListCustomersResponse\x12+\n" +
	"\tcustomers\x18\x01 \x03(\v2\r.web.CustomerR\tcustomers\"\xa2\x01\n" +
	"\x15CreateCustomerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x123\n" +
	"\fcountry_code\x18\x05 \x01(\x0e2\x10.web.CountryCodeR\vcountryCode\"\x18\n" +
	"\x16CreateCustomerResponse\"\xa2\x01\n" +
	"\x15UpdateCustomerRequest\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x123\n" +
	"\fcountry_code\x18\x06 \x01(\x0e2\x10.web.CountryCodeR\vcountryCode\"\x18\n" +
	"\x16UpdateCustomerResponse\"\x17\n" +
	"\x15DeleteCustomerRequest\"\x18\n" +
	"\x16DeleteCustomerResponse\"\xa5\x01\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06street\x18\x04 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x123\n" +
	"\fcountry_code\x18\x06 \x01(\x0e2\x10.web.CountryCodeR\vcountryCode*\xdf\x01\n" +
	"\vCountryCode\x12\x1c\n" +
	"\x18COUNTRY_CODE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03USA\x10\x01\x12\a\n" +
	"\x03JPN\x10\x02\x12\a\n" +
	"\x03DEU\x10\x03\x12\a\n" +
	"\x03FRA\x10\x04\x12\a\n" +
	"\x03GBR\x10\x05\x12\a\n" +
	"\x03CAN\x10\x06\x12\a\n" +
	"\x03AUS\x10\a\x12\a\n" +
	"\x03ITA\x10\b\x12\a\n" +
	"\x03BRA\x10\t\x12\a\n" +
	"\x03KOR\x10\n" +
	"\x12\a\n" +
	"\x03CHN\x10\v\x12\a\n" +
	"\x03IND\x10\f\x12\a\n" +
	"\x03MEX\x10\r\x12\a\n" +
	"\x03RUS\x10\x0e\x12\a\n" +
	"\x03ESP\x10\x0f\x12\a\n" +
	"\x03NLD\x10\x10\x12\a\n" +
	"\x03SWE\x10\x11\x12\a\n" +
	"\x03CHE\x10\x12\x12\a\n" +
	"\x03ARG\x10\x13\x12\a\n" +
	"\x03ZAF\x10\x14B\vZ\tproto/webb\x06proto3"

var (
	file_proto_web_customer_proto_rawDescOnce sync.Once
	file_proto_web_customer_proto_rawDescData []byte
)

func file_proto_web_customer_proto_rawDescGZIP() []byte {
	file_proto_web_customer_proto_rawDescOnce.Do(func() {
		file_proto_web_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_web_customer_proto_rawDesc), len(file_proto_web_customer_proto_rawDesc)))
	})
	return file_proto_web_customer_proto_rawDescData
}

var file_proto_web_customer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_web_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_web_customer_proto_goTypes = []any{
	(CountryCode)(0),               // 0: web.CountryCode
	(*GetCustomerRequest)(nil),     // 1: web.GetCustomerRequest
	(*GetCustomerResponse)(nil),    // 2: web.GetCustomerResponse
	(*ListCustomersRequest)(nil),   // 3: web.ListCustomersRequest
	(*ListCustomersResponse)(nil),  // 4: web.ListCustomersResponse
	(*CreateCustomerRequest)(nil),  // 5: web.CreateCustomerRequest
	(*CreateCustomerResponse)(nil), // 6: web.CreateCustomerResponse
	(*UpdateCustomerRequest)(nil),  // 7: web.UpdateCustomerRequest
	(*UpdateCustomerResponse)(nil), // 8: web.UpdateCustomerResponse
	(*DeleteCustomerRequest)(nil),  // 9: web.DeleteCustomerRequest
	(*DeleteCustomerResponse)(nil), // 10: web.DeleteCustomerResponse
	(*Customer)(nil),               // 11: web.Customer
}
var file_proto_web_customer_proto_depIdxs = []int32{
	11, // 0: web.GetCustomerResponse.customer:type_name -> web.Customer
	11, // 1: web.ListCustomersResponse.customers:type_name -> web.Customer
	0,  // 2: web.CreateCustomerRequest.country_code:type_name -> web.CountryCode
	0,  // 3: web.UpdateCustomerRequest.country_code:type_name -> web.CountryCode
	0,  // 4: web.Customer.country_code:type_name -> web.CountryCode
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_web_customer_proto_init() }
func file_proto_web_customer_proto_init() {
	if File_proto_web_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_web_customer_proto_rawDesc), len(file_proto_web_customer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_web_customer_proto_goTypes,
		DependencyIndexes: file_proto_web_customer_proto_depIdxs,
		EnumInfos:         file_proto_web_customer_proto_enumTypes,
		MessageInfos:      file_proto_web_customer_proto_msgTypes,
	}.Build()
	File_proto_web_customer_proto = out.File
	file_proto_web_customer_proto_goTypes = nil
	file_proto_web_customer_proto_depIdxs = nil
}
