// Code generated by MockGen. DO NOT EDIT.
// Source: customer.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/tusmasoma/go-microservice-k8s/services/customer/entity"
	usecase "github.com/tusmasoma/go-microservice-k8s/services/customer/usecase"
)

// MockCustomerUseCase is a mock of CustomerUseCase interface.
type MockCustomerUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerUseCaseMockRecorder
}

// MockCustomerUseCaseMockRecorder is the mock recorder for MockCustomerUseCase.
type MockCustomerUseCaseMockRecorder struct {
	mock *MockCustomerUseCase
}

// NewMockCustomerUseCase creates a new mock instance.
func NewMockCustomerUseCase(ctrl *gomock.Controller) *MockCustomerUseCase {
	mock := &MockCustomerUseCase{ctrl: ctrl}
	mock.recorder = &MockCustomerUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerUseCase) EXPECT() *MockCustomerUseCaseMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method.
func (m *MockCustomerUseCase) CreateCustomer(ctx context.Context, params *usecase.CreateCustomerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockCustomerUseCaseMockRecorder) CreateCustomer(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockCustomerUseCase)(nil).CreateCustomer), ctx, params)
}

// DeleteCustomer mocks base method.
func (m *MockCustomerUseCase) DeleteCustomer(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCustomer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCustomer indicates an expected call of DeleteCustomer.
func (mr *MockCustomerUseCaseMockRecorder) DeleteCustomer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCustomer", reflect.TypeOf((*MockCustomerUseCase)(nil).DeleteCustomer), ctx, id)
}

// GetCustomer mocks base method.
func (m *MockCustomerUseCase) GetCustomer(ctx context.Context, id string) (*entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", ctx, id)
	ret0, _ := ret[0].(*entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockCustomerUseCaseMockRecorder) GetCustomer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockCustomerUseCase)(nil).GetCustomer), ctx, id)
}

// ListCustomers mocks base method.
func (m *MockCustomerUseCase) ListCustomers(ctx context.Context) ([]entity.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCustomers", ctx)
	ret0, _ := ret[0].([]entity.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCustomers indicates an expected call of ListCustomers.
func (mr *MockCustomerUseCaseMockRecorder) ListCustomers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCustomers", reflect.TypeOf((*MockCustomerUseCase)(nil).ListCustomers), ctx)
}

// UpdateCustomer mocks base method.
func (m *MockCustomerUseCase) UpdateCustomer(ctx context.Context, params *usecase.UpdateCustomerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCustomer", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCustomer indicates an expected call of UpdateCustomer.
func (mr *MockCustomerUseCaseMockRecorder) UpdateCustomer(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCustomer", reflect.TypeOf((*MockCustomerUseCase)(nil).UpdateCustomer), ctx, params)
}
