name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "go/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "go/**"
  workflow_dispatch:

jobs:
  discover-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.discover.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0
        with:
          fetch-depth: 0

      - name: Discover Go Services
        id: discover
        uses: ./.github/actions/discover-services
  build:
    needs: discover-services
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover-services.outputs.matrix) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.0.0
        id: setup-go
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - name: Download Go modules
        shell: bash
        if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
        working-directory: ./go/services/${{ matrix.service }}
        run: |
          go mod download
          go mod verify

      - name: Build
        working-directory: ./go/services/${{ matrix.service }}
        run: |
          go build -v -o app ./cmd/

      - name: Archive production artifacts
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        with:
          name: app-${{ matrix.service }}
          path: ./go/services/${{ matrix.service }}/app
  test:
    needs:
      - discover-services
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover-services.outputs.matrix) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.0.0
        with:
          name: app-${{ matrix.service }}
          path: ./go/services/${{ matrix.service }}/app

      - name: Test
        run: make test SERVICE=${{ matrix.service }}
  lint:
    needs:
      - discover-services
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover-services.outputs.matrix) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.0.0
        with:
          name: app-${{ matrix.service }}
          path: ./go/services/${{ matrix.service }}/app

      - name: Lint
        run: make lint SERVICE=${{ matrix.service }}