name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "go/**"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [ "main" ]
    paths:
      - "go/**"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

jobs:
  discover-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.discover.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0
        with:
          fetch-depth: 0

      - name: Discover Go Services
        id: discover
        uses: ./.github/actions/discover-services
  test:
    needs: discover-services
    if: ${{ needs.discover-services.outputs.matrix != '{}' && fromJson(needs.discover-services.outputs.matrix).include != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover-services.outputs.matrix) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0
      
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: ./go.mod
          cache: false
      
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.0.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.service }}-${{ hashFiles(format('go/services/{0}/go.sum', matrix.service), 'go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.service }}-

      - name: Test
        run: make test SERVICE=${{ matrix.service }}
  lint:
    needs:
      - discover-services
      - test
    if: ${{ needs.discover-services.outputs.matrix != '{}' && fromJson(needs.discover-services.outputs.matrix).include != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.discover-services.outputs.matrix) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: ./go.mod
          cache: false
      
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.0.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.service }}-${{ hashFiles(format('go/services/{0}/go.sum', matrix.service), 'go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.service }}-

      - name: Lint (diff only for PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
        with:
          version: v1.63.4
          args: -v --timeout=20m ./go/services/${{ matrix.service }}/...

      - name: Lint (full for non-PR)
        if: ${{ github.event_name != 'pull_request' }}
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
        with:
          version: v1.63.4
          args: --timeout=20m -v ./...